### ISSUE TITLE
`save_state` opinion

### ISSUE THREAD

**Issue by blazkowolf** [fraso-dev/nvim-listchars#2]
Hey! If I can offer my humble opinion - I think `save_state` is unnecessary. 

For example, if someone wants the plugin disabled on start, they can simply pass the `enable = false` option to the config and toggle it on when they want with `ListcharsToggle`. 

I really like the work you did to integrate file I/O with cached user preferences, but I think it's slightly over-engineered for the problem you're trying to solve. 

I think it's a non-issue for the user, unless you thought of a use-case I'm not seeing.

**Comment by 0xfraso** [comment]
The reason I introduced this feature is that I found myself tweaking a lot my neovim config files just to toggle the default behaviour of some "toggling" plugins.
I just wanted to keep the user aware of the possibility of using `enable` to set plugin's default behaviour (as I did before), and keep the state of the plugin by using `save_state` (that should always be left on `true` in my opinion)
This way I can keep the state saved until I toggle it back, for example when working on plain text files/notes in which I don't want listchars displayed.

Speaking of "toggling-like" plugins, I just opened a pull request introducing the same feature in [this](https://github.com/xiyaowong/nvim-transparent/pull/26) plugin (that may be a more reasonable use-case)

In both cases, the most annoying thing for me is to keep my dotfiles' git history clean when toggling back and forth those boolean values.

**Comment by blazkowolf** [comment]
That makes a lot of sense - in that case, it might make sense to leave that as the default behavior without introducing a flag - but I totally understand if you want the option to be there.

**Comment by 0xfraso** [comment]
Do you think this should be the default behavior? Or maybe It just needs a better explanation in the README

**Comment by blazkowolf** [comment]
Personally, I think it should. You could leave the `save_state = true` as the default and then in the README advertise that the user can disable that default behavior.

I guess my main confusion with it drew from the fact that pluin managers like packer and lazy give the option to specify a plugin, but have it be enabled or disabled on startup. Then listchars has its own option to be enabled or disabled at runtime.

But your explanation makes total sense. I'm just thinking to myself if there's a more straightforward way of conveying that information.

I apologize if I'm derailing things. Your work is awesome!

**Comment by 0xfraso** [comment]
I think your confusion is legitimately driven by the lack of explanation in the docs.

All plugin managers setup conventions want users to be aware of the defaults starting from a "suggested" configuration that is usually a list of defaults.

That's why I think It's just a matter of understanding how to proper configure plugins and not just copy pasting configs from the docs.

Anyway, just updated README [145769a](https://github.com/fraso-dev/nvim-listchars/commit/145769af49ca9cf4598773ab073a511278edd813)

Thanks a lot for your feedback and help!
